// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PriceCPT.Infraestrutura;

#nullable disable

namespace PriceCPT.Migrations
{
    [DbContext(typeof(ConexaoContext))]
    [Migration("20250506191059_CriarTabelaProdutoEAlteracao")]
    partial class CriarTabelaProdutoEAlteracao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PriceCPT.Domain.Models.AlteracaoProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("dataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("preco_antigo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("preco_novo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("id_produto")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("id_produto");

                    b.ToTable("AlteracaoProduto");
                });

            modelBuilder.Entity("PriceCPT.Domain.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("produto");
                });

            modelBuilder.Entity("PriceCPT.Domain.Models.Usuario", b =>
                {
                    b.Property<int>("ID_USUARIO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID_USUARIO"));

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NOME")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SENHA")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID_USUARIO");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("PriceCPT.Domain.Models.AlteracaoProduto", b =>
                {
                    b.HasOne("PriceCPT.Domain.Models.Produto", "Produto")
                        .WithMany("AlteracaoProdutos")
                        .HasForeignKey("id_produto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("PriceCPT.Domain.Models.Produto", b =>
                {
                    b.Navigation("AlteracaoProdutos");
                });
#pragma warning restore 612, 618
        }
    }
}
