// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PriceCPT.Infraestrutura;

#nullable disable

namespace PriceCPT.Migrations
{
    [DbContext(typeof(ConexaoContext))]
    partial class ConexaoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PriceCPT.Domain.Models.AlteracaoPreco", b =>
                {
                    b.Property<int>("id_preco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_preco"));

                    b.Property<DateTime>("data_alteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("estoque")
                        .HasColumnType("int");

                    b.Property<int>("id_produto")
                        .HasColumnType("int");

                    b.Property<decimal>("preco_antigo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("preco_novo")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("id_preco");

                    b.HasIndex("id_produto");

                    b.ToTable("alteracao_preco");
                });

            modelBuilder.Entity("PriceCPT.Domain.Models.Produto", b =>
                {
                    b.Property<int>("id_produto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_produto"));

                    b.Property<DateTime>("data_cadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("estoque")
                        .HasColumnType("int");

                    b.Property<string>("imagem_url")
                        .HasColumnType("longtext");

                    b.Property<string>("mlb")
                        .HasColumnType("longtext");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("preco")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("id_produto");

                    b.ToTable("produto");
                });

            modelBuilder.Entity("PriceCPT.Domain.Models.Usuario", b =>
                {
                    b.Property<int>("ID_USUARIO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID_USUARIO"));

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NOME")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SENHA")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID_USUARIO");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("PriceCPT.Domain.Models.AlteracaoPreco", b =>
                {
                    b.HasOne("PriceCPT.Domain.Models.Produto", "produto")
                        .WithMany("alteracaoProdutos")
                        .HasForeignKey("id_produto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("produto");
                });

            modelBuilder.Entity("PriceCPT.Domain.Models.Produto", b =>
                {
                    b.Navigation("alteracaoProdutos");
                });
#pragma warning restore 612, 618
        }
    }
}
